"""Add tel to banner

Revision ID: 1294feeb356e
Revises: ca356ca07a1b
Create Date: 2026-01-16 03:49:58.320798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1294feeb356e'
down_revision = 'ca356ca07a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tel', sa.String(length=30), nullable=True))
        batch_op.drop_column('price')
        batch_op.drop_column('currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=True))
        batch_op.drop_column('tel')

    # ### end Alembic commands ###
