"""add currency to product

Revision ID: 441d7cf8f178
Revises: f7306dc13bb5
Create Date: 2026-01-15 03:07:06.998207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441d7cf8f178'
down_revision = '02df633d5649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
