"""add cta_color to banner

Revision ID: 4cede9cab3ac
Revises: eb59f40d913c
Create Date: 2026-01-16 06:11:02.599383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cede9cab3ac'
down_revision = 'eb59f40d913c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cta_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.drop_column('cta_color')

    # ### end Alembic commands ###
