"""add product badges

Revision ID: 4e1d0cd49ba7
Revises: 8e51fcc8b201
Create Date: 2026-01-12 17:01:06.983271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1d0cd49ba7'
down_revision = '8e51fcc8b201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_trending', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_on_sale', sa.Boolean(), nullable=True))
        batch_op.alter_column('name_fr',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('description_fr',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('description_fr',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('name_fr',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('is_on_sale')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('is_trending')
        batch_op.drop_column('is_new')

    # ### end Alembic commands ###
