"""add category icon nullable

Revision ID: 6a99c7241dbd
Revises: 4e1d0cd49ba7
Create Date: 2026-01-13 04:06:49.242057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a99c7241dbd'
down_revision = '4e1d0cd49ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
