"""Add shop name and location to product

Revision ID: a5353ed2f49f
Revises: 4cede9cab3ac
Create Date: 2026-01-17 04:42:34.659174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5353ed2f49f'
down_revision = '4cede9cab3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('shop_location', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('shop_location')
        batch_op.drop_column('shop_name')

    # ### end Alembic commands ###
