"""add cta_text to banner

Revision ID: eb59f40d913c
Revises: 1294feeb356e
Create Date: 2026-01-16 05:57:26.264369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb59f40d913c'
down_revision = '1294feeb356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cta_text', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner', schema=None) as batch_op:
        batch_op.drop_column('cta_text')

    # ### end Alembic commands ###
